#
trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '12-CI-CD-Pipelines/Azure-DevOps/AKS'
    commandOptions: '-var="Name=$(Name)" -var="resourceGroup=$(resourceGroup)" -var="clientID=$(clientID)" -var="clientSecret=$(clientSecret)" -var="location=$(location)"'
    backendServiceArm: 'Visual Studio Enterprise Subscription(4611ca1e-866d-48a2-9c61-bb92d9be1fe9)'
    backendAzureRmResourceGroupName: 'terraformstate-rg'
    backendAzureRmStorageAccountName: 'terrastatestore101022'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.state'

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '12-CI-CD-Pipelines/Azure-DevOps/AKS'
    commandOptions: '-var="Name=$(Name)" -var="resourceGroup=$(resourceGroup)" -var="clientID=$(clientID)" -var="clientSecret=$(clientSecret)" -var="location=$(location)"'
    environmentServiceNameAzureRM: 'Visual Studio Enterprise Subscription(4611ca1e-866d-48a2-9c61-bb92d9be1fe9)'
